name: Create new pull request
on:
  push:
    branches:
      - 'development'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: pull-request
