name: Create new pull request
on:
  push:
    branches:
      - 'feature'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "feature"
          destination_branch: "development"
          github_token: ${{ secrets.GITHUB_TOKEN }}
