name: Feature Branch CI
on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'


jobs:
  testui:
    runs-on: ubuntu-latest
    steps:
      - uses: vgaidarji/android-github-actions-emulator@v1.0.1

  testlocal:
    runs-on: ubuntu-latest
    name: Run Unit test

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace
